<?php
$BODY.='
<p><input></p>
<p><textarea></textarea></p>
<p><input></p>
<p><textarea></textarea></p>
<p><input></p>
<p><textarea></textarea></p>
<p><input></p>
<p><textarea></textarea></p>
<p><input></p>
<p><textarea></textarea></p>
<p><input></p>
<p><textarea></textarea></p>
';
?>